### ISSUE TITLE
How open？

### ISSUE THREAD

**Issue by BestDreamy** [fxfxfxfxfxfxfxfx/Graduation-thesis-proposal-report-template#1]
Can you open this repo in overleaf?

**Comment by fxfxfxfxfxfxfxfx** [comment]
Although I have not tried it on overleaf, it should be possible. However, when the files you want to compile have a lot of content and you happen to not have a distinguished member, you may face a compilation timeout.

**Comment by fxfxfxfxfxfxfxfx** [comment]
> Can you open this repo in overleaf?

0.o

**Comment by BestDreamy** [comment]
Thanks for your answer, sir.
